# Generated by Django 5.0.7 on 2024-07-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='rssdata',
            name='id_rss_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.rssurls'),
        ),
    ]
