# Generated by Django 5.0.7 on 2024-07-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_delete_users_rssdata_id_rss_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsJunction',
            fields=[
                ('junc_id', models.AutoField(primary_key=True, serialize=False)),
                ('rss_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.rssdata')),
                ('rss_skills_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.rssskills')),
            ],
        ),
    ]
