# Generated by Django 5.0.7 on 2024-07-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rssskills_skillsjunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssdata',
            name='id_rss_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.rssurls'),
        ),
    ]
